name: Deploy Lambda

on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Compile TypeScript to JavaScript
      run: npm run build

    - name: Package Lambda
      run: |
        mkdir -p dist
        cp -R node_modules dist/node_modules
        cp -R package.json dist/package.json
        cd dist && zip -r function.zip *

    - name: Deploy to S3
      run: aws s3 cp dist/function.zip s3://lambdasbucket-test-lab-gtk/lambdas/lambda-gh-actions.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'sa-east-1'

    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \
          --template-file './.github/workflows/ci-cd/template.yaml' \
          --stack-name lambda-gh-actions-test \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides DeploymentBucket=lambdasbucket-test-lab-gtk DeploymentKey=lambdas/lambda-gh-actions.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'sa-east-1'
