AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DeploymentBucket:
    Type: String
    Description: The S3 bucket where the Lambda code is stored
  DeploymentKey:
    Type: String
    Description: The S3 key for the Lambda code

Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lambda-gh-actions-test
      Handler: index.handler
      Runtime: nodejs12.x
      Code:
        S3Bucket: !Ref DeploymentBucket
        S3Key: !Ref DeploymentKey
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          NODE_ENV: production
          VALUE: test

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
